### ISSUE TITLE
jim 0.79 - crash in binary scan

### ISSUE THREAD

**Issue by citrus-it** [msteveb/jimtcl#138]
I'm testing upgrading Jim to 0.79 and my code is causing jim to crash with a bus error.

Here's a test script:

```tcl
package require binary
set bytes {1 2 3 4}
binary scan $bytes H* hex
```

and the stack:

```
#0  0x2af06f54 in free () from /lib/libc.so.0
#1  0x00407fc8 in Jim_Free (ptr=0x1) at jim.c:659
#2  0x0040c11c in Jim_FreeObj (interp=0x464008, objPtr=0x4848d8) at jim.c:2193
#3  0x004216f8 in JimInvokeCommand (interp=0x464008, objc=3, objv=0x7fe434fc)
    at jim.c:10155
#4  0x00422c74 in Jim_EvalObj (interp=0x464008, scriptObjPtr=0x482930)
    at jim.c:10619
#5  0x0042686c in Jim_LoopCoreCommand (interp=0x464008, argc=5,
    argv=0x7fe43644) at jim.c:11790
#6  0x00421764 in JimInvokeCommand (interp=0x464008, objc=5, objv=0x7fe43644)
    at jim.c:10161
#7  0x00422c74 in Jim_EvalObj (interp=0x464008, scriptObjPtr=0x46cd90)
    at jim.c:10619
#8  0x00428118 in Jim_SwitchCoreCommand (interp=0x464008, argc=5,
    argv=0x7fe43774) at jim.c:12194
#9  0x00421764 in JimInvokeCommand (interp=0x464008, objc=5, objv=0x7fe43774)
    at jim.c:10161
#10 0x00422c74 in Jim_EvalObj (interp=0x464008, scriptObjPtr=0x46f180)
    at jim.c:10619
#11 0x0042718c in JimForeachMapHelper (interp=0x464008, argc=4,
    argv=0x7fe438c4, doMap=0) at jim.c:11945
#12 0x00427308 in Jim_ForeachCoreCommand (interp=0x464008, argc=4,
    argv=0x7fe438c4) at jim.c:11974
#13 0x00421764 in JimInvokeCommand (interp=0x464008, objc=4, objv=0x7fe438c4)
    at jim.c:10161
#14 0x00422c74 in Jim_EvalObj (interp=0x464008, scriptObjPtr=0x47d890)
    at jim.c:10619
#15 0x00423898 in JimCallProcedure (interp=0x464008, cmd=0x47cad8, argc=4,
    argv=0x47eae8) at jim.c:10863
#16 0x0042172c in JimInvokeCommand (interp=0x464008, objc=4, objv=0x47eae8)
    at jim.c:10157
#17 0x004222f0 in JimEvalObjList (interp=0x464008, listPtr=0x47d5c8)
    at jim.c:10404
#18 0x0042237c in Jim_EvalObjList (interp=0x464008, listPtr=0x47d5c8)
    at jim.c:10415
#19 0x00423928 in JimCallProcedure (interp=0x464008, cmd=0x47cc40, argc=5,
    argv=0x7fe43acc) at jim.c:10880
#20 0x0042172c in JimInvokeCommand (interp=0x464008, objc=5, objv=0x7fe43acc)
    at jim.c:10157
#21 0x00422c74 in Jim_EvalObj (interp=0x464008, scriptObjPtr=0x473890)
    at jim.c:10619
#22 0x00423f50 in Jim_EvalFile (interp=0x464008,
    filename=0x7fe43e5e "test.jim") at jim.c:11012
#23 0x00406090 in main (argc=2, argv=0x7fe43d64) at jimsh.c:140
```

**Comment by msteveb** [comment]
I can't reproduce this. Running under valgrind shows no problems. Can you make sure you started with a clean build? Also try adding ./configure --maintainer

**Comment by citrus-it** [comment]
I'll do some more digging and report back - definitely reproducible here when starting from a clean build.

**Comment by msteveb** [comment]
OK, let me know what you find.

**Comment by citrus-it** [comment]
It turns out that, for reasons I won't go into, an old pack.so file was being found and loaded (one from a very old version of jim). Once I removed that, everything is working fine.

Sorry for the noise.
