### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value

### ISSUE THREAD

**Issue by tankf33der** [msteveb/jimtcl#147]
run tests under clang+sanitizers

```
    lsearch.test: Total    44   Passed    43  Skipped     0  Failed     1
------------------------------------------------------------
FAILED: 1
	lsearch.test:50	lsearch-2.6
------------------------------------------------------------
==25775==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5652d8b3ab0b in ListSortStringNoCase /home/mpech/jimtcl/jim.c:6609:52
    #1 0x7f10f889e774 in msort_with_tmp.part.0 (/usr/lib/libc.so.6+0x3d774)
    #2 0x7f10f889e701 in msort_with_tmp.part.0 (/usr/lib/libc.so.6+0x3d701)
    #3 0x7f10f889eaa5 in qsort_r (/usr/lib/libc.so.6+0x3daa5)
    #4 0x5652d8b3a036 in ListSortElements /home/mpech/jimtcl/jim.c:6744:9
    #5 0x5652d8b02db6 in Jim_LsortCoreCommand /home/mpech/jimtcl/jim.c:12575:15
    #6 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #7 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #8 0x5652d8b05390 in Jim_UplevelCoreCommand /home/mpech/jimtcl/jim.c
    #9 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #10 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #11 0x5652d8b15a3b in Jim_CatchCoreCommand /home/mpech/jimtcl/jim.c:13833:20
    #12 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #13 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #14 0x5652d8acb062 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10512:35
    #15 0x5652d8af21b3 in JimCallProcedure /home/mpech/jimtcl/jim.c:10823:15
    #16 0x5652d8ac8cf9 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10117:19
    #17 0x5652d8af23c5 in JimEvalObjList /home/mpech/jimtcl/jim.c:10364:19
    #18 0x5652d8af23c5 in Jim_EvalObjList /home/mpech/jimtcl/jim.c:10375:12
    #19 0x5652d8af23c5 in JimCallProcedure /home/mpech/jimtcl/jim.c:10840:27
    #20 0x5652d8ac8cf9 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10117:19
    #21 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #22 0x5652d8ad2f9c in Jim_EvalFile /home/mpech/jimtcl/jim.c:10972:15
    #23 0x5652d8b300fd in Jim_SourceCoreCommand /home/mpech/jimtcl/jim.c:15083:14
    #24 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #25 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #26 0x5652d8b680f6 in interp_cmd_eval /home/mpech/jimtcl/jim-interp.c:36:11
    #27 0x5652d8b76466 in Jim_CallSubCmd /home/mpech/jimtcl/jim-subcmd.c
    #28 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #29 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #30 0x5652d8b15a3b in Jim_CatchCoreCommand /home/mpech/jimtcl/jim.c:13833:20
    #31 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #32 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #33 0x5652d8af9e30 in Jim_IfCoreCommand /home/mpech/jimtcl/jim.c
    #34 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #35 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #36 0x5652d8b393ec in JimForeachMapHelper /home/mpech/jimtcl/jim.c:11905:26
    #37 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #38 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #39 0x5652d8af9e30 in Jim_IfCoreCommand /home/mpech/jimtcl/jim.c
    #40 0x5652d8ac9163 in JimInvokeCommand /home/mpech/jimtcl/jim.c:10121:19
    #41 0x5652d8acb949 in Jim_EvalObj /home/mpech/jimtcl/jim.c:10579:23
    #42 0x5652d8ad2f9c in Jim_EvalFile /home/mpech/jimtcl/jim.c:10972:15
    #43 0x5652d8a93441 in main /home/mpech/jimtcl/jimsh.c:143:27
    #44 0x7f10f8888152 in __libc_start_main (/usr/lib/libc.so.6+0x27152)
    #45 0x5652d8a174ed in _start (/home/mpech/jimtcl/jimsh+0x2a4ed)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/mpech/jimtcl/jim.c:6609:52 in ListSortStringNoCase
Exiting
```

**Comment by msteveb** [comment]
Thanks for the report. What version? What platform?
What tests are you running? If it's only lsearch.test, it seems very strange that you see a problem in lsort since none of those tests use lsort. Can you narrow it down to one test case?

**Comment by tankf33der** [comment]
Manjaro Linux, x64, clang, master trunk.
Sad I cant repeat it anymore.

**Comment by msteveb** [comment]
OK, thanks. Probably not much I can do with it then. If you can reproduce anything, let me know.
